//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.07.22 at 09:48:55 PM ICT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://soap.jee.meh.com/", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.meh.jee.soap;
